[package]
name = "preprocess"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "preprocess"
path = "src/main.rs"

[dependencies]
common.workspace = true
flate2.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true

[lints]
workspace = true
